### PR TITLE
Build and publish docker image

### PR DESCRIPTION
**Pull request by yujunz**
Build docker image and push to GitHub package to allow using these tools in container world like Kubernetes.

### CODE REVIEW

**Comment by yujunz** [comment]
It is awkward to find out that even [pulling public packages in GitHub requires authentication](https://github.community/t5/GitHub-Actions/docker-pull-from-public-GitHub-Package-Registry-fail-with-quot/m-p/32888#M1294).

If needed I can change it to push to docker hub instead.

**Comment by billziss-gh** [comment]
Thanks for the PR. I am looking at it now.

I am thinking it may make more sense to publish the Docker image independently (possibly on DocketHub) and then I am happy to link to it from the README. What do you think?

**Comment by yujunz** [comment]
It is also published at https://hub.docker.com/r/yujunz/secfs.test and can be pull with `docker pull yujunz/secfs.test`.

Feel free to link to it in README.

**Comment by billziss-gh** [comment]
I have added a link to the [README](https://github.com/billziss-gh/secfs.test#docker-image).

Thanks again.

**Pull request closed without merging**
